# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 820d2ceb7f1fed1b1319edd5c13c4227ceb83415de71e0fddbcba6a1ca4cb3d7d349f39c75a2140b68fe1e4181c8d65e6d62e0c5a60a56a0efe379da20a84913

test:
  secret_key_base: 56a6d969502acf7a5c8a411fca186634a018587594884b060b47611fb442bd5ac7eab72d1a5e13ba918fc54942831d6a7183fff7d88a7342380efc2dc4712f7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
